-- V1__Init_DB.sql

CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         price INTEGER NOT NULL
);

-- Можно сразу добавить начальные данные (чтобы не писать их в Java коде)
INSERT INTO product (name, price) VALUES ('iPhone 15', 1200);
INSERT INTO product (name, price) VALUES ('Samsung S24', 1100);
INSERT INTO product (name, price) VALUES ('Nokia 3310', 50);