-- Создаем таблицу пользователей
-- Называем app_user, потому что слово "user" зарезервировано в PostgreSQL
CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          role VARCHAR(255) NOT NULL
);

-- Добавляем Админа
-- Пароль пока пишем в открытую (это плохо, но на следующем шаге мы это исправим)
INSERT INTO app_user (username, password, role)
VALUES ('admin', '$2a$10$NotEncodedYetButWillBeSoon', 'ADMIN');

-- Добавляем обычного юзера
INSERT INTO app_user (username, password, role)
VALUES ('user', '$2a$10$NotEncodedYetButWillBeSoon', 'USER');